### ISSUE TITLE
Setup a node with hardhat

### ISSUE THREAD

**Issue by jpalvarezl** [gnosis/safe-indexer#1]
Setup a local node using hardhat and the https://github.com/gnosis/safe-contracts repository.

Additionally, deploying locally other chains such as BSC is also possible. Look into what is possible with hardhat and syncing with other chains.

**Comment by rmeissner** [comment]
In my opinion this repository should only require to provide a rpc endpoint. To run a node as a fork of an existing chain you would use the "forking" from hardhat: https://hardhat.org/hardhat-network/guides/mainnet-forking.html But I don't think this should be the focus of this repository

**Comment by jpalvarezl** [comment]
Agreed.
